### ISSUE TITLE
Constants TCIOFLUSH, TCIFLUSH, TCOFLUSH incorrect on Linux

### ISSUE THREAD

**Issue by notinaboat** [kdheepak/Termios.jl#6]
See
https://github.com/lattera/glibc/blob/895ef79e04a953cac1493863bcae29ad85657ee1/sysdeps/unix/sysv/linux/bits/termios.h#L208-L210
vs

https://github.com/kdheepak/TERMIOS.jl/blob/3c32ffde07fcc9223e7fe139afb7040d460074f6/src/TERMIOS.jl#L421-L428

**Comment by kdheepak** [comment]
Huh, that’s strange. I thought I had put in an if else for all the values that were different for Linux. 

Can you submit a PR? If not, I’ll make the change tomorrow.

**Comment by notinaboat** [comment]
Hi @kdheepak, I won't be able to submit a PR in the next week or so due to competing priorities.

**Comment by notinaboat** [comment]
Hi @kdheepak, you may be interested in this as an alternative to hand-coding constants: https://github.com/notinaboat/CInclude.jl

**Comment by kdheepak** [comment]
Yeah that looks like a good package! I’ll have to refactor and experiment with it. I’m also juggling tasks so I’m not sure when I’ll get to this though.
