### ISSUE TITLE
Document the use of the V* constants for the `c_cc` field

### ISSUE THREAD

**Issue by notthetup** [kdheepak/Termios.jl#8]
The use of the V* constants like `VMIN` and `VTIME` isn't well documented and can lead to an off-by-one error since Julian arrays are 1-based indexed, while the constants are the same as the `libc` versions which are for 0-based indexing arrays.

So doing something like this, which is very intuitive, sets the incorrect value in the struct.

```  
opts = T.termios()
opts.c_cc[T.VMIN] = 0
opts.c_cc[T.VTIME] = 1
```

**Comment by kdheepak** [comment]
I see, that makes sense, I didn’t think about that. Would you like to submit a PR? It’s only a couple of lines that you’ll have to modify.

**Comment by notthetup** [comment]
Sure. I can raise a PR. What do you think is a better approach to fix this? 

- Change the values of the V* constants.
- Do the index conversion in the `getindex`, `setindex` methods.

I am leaning towards the later..

I'll also try to add an example to the documentation.

**Comment by kdheepak** [comment]
I'm up for the latter! Thanks for offering to submit a PR!

**Comment by notthetup** [comment]
Thanks @kdheepak!
